### ISSUE TITLE
Unable To Run Downloader

### ISSUE THREAD

**Issue by deadbeatdandylyon** [Avnsx/fansly-downloader#101]
I have always been able to use the Fansly Scraper but it seems that now after the update I can no longer run the downloader, The following are the steps I've taken so far. 

1) In my original download directory where the fansly scraper was it did mention I needed to run the update, So I ran the update, updated the auto configuration application, updated the user name of the creator and then went to select "Fansly Downloader" the cmd window just opened and closed after a few seconds so I thought I was doing something wrong. 

2) the next thing I did was visit this page and downloaded the "Fansly_Downloader_0.4-Windows" download and unzipped it in another directory updated the configuration file with the correct information and the cmd window again just opened and closed. 

I was able to get a screen shot of the error when I use the "Fansly Downloader" application 

![Fansly_Downloader_0 4-Windows 6_12_2023 10_30_04 PM (2)](https://github.com/Avnsx/fansly-downloader/assets/59564520/bedd3fce-43b0-403c-b702-d1cd85c84335)

However I did test and the only way I was able to run it was using the older "Fansly Scraper" Application. 

My question which downloader SHOULD I be using? or does it not matter? or is the "Fansly Downloader" application only if I were to have went with the python setup route?

**Comment by deadbeatdandylyon** [comment]
Windows 11 Home 64bit version 22H2

**Comment by Avnsx** [comment]
Are you maybe usint anti-virus programs such as Avira, F-Secure or SecureAge?

**Comment by deadbeatdandylyon** [comment]
I am running Norton Antivirus, however It didn't identify that there was any issues with the files so didn't have to restore anything and it still works with "Fansly Scraper" application

**Comment by Avnsx** [comment]
When you run the in version 0.4 provided updater.exe, do you also get any errors, or does it just as intended, attempt to start the Fansly Downloader application?

**Comment by Avnsx** [comment]
I did a little bit of research and it turns out it might be a issue with me compiling the 0.4 version of Fanlsy Downloader using Python 3.8.10.

Based on the information provided in this issue ticket (https://github.com/pyinstaller/pyinstaller/issues/7309#issuecomment-1340750097), it appears that there is a bug related to PyAV and earlier versions of Python. The individual who raised the issue mentions that they are using Python supplied by Anaconda, which they believe is the underlying cause of the problem. To potentially resolve this issue and any future occurrences, it might be worth considering compiling Fansly Downloader with the latest version of Python, specifically Python 3.11.2. However, it's important to note that this would make Windows 7 incompatible with Fansly Downloader. It's worth mentioning that despite testing the executable on Windows 10 and 11 before release, this error never occurred, which adds to the confusion.

Here's a version of Fansly Downloader that was compiled with Python 3.11.2 on Windows 11, let me know if this version works properly for you: https://github.com/Avnsx/test-repository/releases/download/v0.4/Fansly_Downloader_0.4-Windows_python3.11.2.zip

**Comment by Avnsx** [comment]
> Well as I have mentioned before the older "Fansly Scraper" application before the change that updater/scraper are working perfectly fine.

The older version is working fine, because at the time of developing that version there was no point for me to introduce the usage of the python module PyAV, which is currently used in the new version of fansly downloader to stay compatible (transcode the new video file format from .m3u8 to .mp4) with fanslys may 2023 update, in which they introduced the .m3u8 file format for videos.

> So with that being said I guess whats important to know is going forward will I still be able to use Fansly Scraper.exe as it is working or will I at some point have to switch over to the Fansly Downloader.exe

There's no way you would want to stay on the old 0.3.5 version "Fansly Scraper.exe", as it's heavily outdated. Yes, you do have to switch over to the new 0.4 version named "Fansly Downloader.exe", which is why I am trying to make it compatible with your and other users systems, that might have the same issue.

It's really hard for me to debug this, because I personally can not re-produce this issue neither on Windows 10 nor on Windows 11. So I am really dependant on your help here.

I think I need to pass this issue on to pyinstaller / pyav repositories and see if I can get any help there, because I personally ran out of ideas on how to fix this compiling issue.

**Comment by deadbeatdandylyon** [comment]
Well if it would help I can try to screen record each step I take if that will help? 

With the .exe download is there anything else that I have to do aside from unzip - run the updater - and do the config file?

**Comment by Avnsx** [comment]
The only thing that would help right now, is knowing if you are even able to run the bare python code of Fansly Downloader version 0.4, which also utilises PyAV.

Here's a tutorial on how to set it up: https://github.com/Avnsx/fansly-downloader#python-version-requirements

**Comment by deadbeatdandylyon** [comment]
So I was able to install all the requirements, however still getting the same error message when either running the updater.exe or fansly downloader.exe

![Screenshot 2023-06-13 080108](https://github.com/Avnsx/fansly-downloader/assets/59564520/400ac067-8977-41bd-bb73-34763bf868c5)

**Comment by Avnsx** [comment]
That's not a error message, that just says that the requirements for the python version were properly installed.
Now all you've to do is click on fansly_downloader.py, which you should've installed by clicking on the text [download the repository](https://github.com/Avnsx/fansly-downloader/archive/refs/heads/main.zip) & unzipped afterwards

**Comment by Avnsx** [comment]
I understand that, but I am refering to the python file "fansly_downloader.py", I am wondering if you can run the bare python file, not the executable .exe files.

**Comment by deadbeatdandylyon** [comment]
> I understand that, but I am refering to the python file "fansly_downloader.py", I am wondering if you can run the bare python file, not the executable .exe files.

I'm not all that familar with python how do I run the file

**Comment by Avnsx** [comment]
> how do I run the file

literally just [download the repository](https://github.com/Avnsx/fansly-downloader/archive/refs/heads/main.zip), extract the .zip folder and just click on the file called ``fansly_downloader.py``

**Comment by Avnsx** [comment]
> So I was able to install all the requirements, however still getting the same error message when either running the updater.exe or fansly downloader.exe
> 
> ![Screenshot 2023-06-13 080108](https://user-images.githubusercontent.com/59564520/245468664-400ac067-8977-41bd-bb73-34763bf868c5.png)

That usually means that you didn't porperly install the requirements or uinstalled them again (maybe uninstalled python too already). Type in ``pip3 install requests loguru python-dateutil plyvel-ci psutil imagehash m3u8 av pillow`` in cmd.exe again and try running the fansly_downloader.py file again

**Comment by deadbeatdandylyon** [comment]
![image](https://github.com/Avnsx/fansly-downloader/assets/59564520/dc55f91e-cd93-4ca0-863c-d4385d4ed256)

So states all the requirements are already satisfied 

I have python version 3.11 installed 

If I try to open Fansly_downloader.py with in cmd I get the following message

![image](https://github.com/Avnsx/fansly-downloader/assets/59564520/e8d8df27-cf73-4489-93cf-1deb76a0c867)

If I just double click on the fansly_downloader.py file in the windows directory it just opens and closes

**Comment by deadbeatdandylyon** [comment]
okay so to provide an update. I rebooted my PC and I was then able to redownload everything and run the python downloader and everything worked with the python route, I did also disable my Norton auto protect and firewall, I re enabled my auto protect and firewall and ran the python script again and it worked, I also downloaded the exe and ran that and everything worked. so a simple reboot and everything is working, 

Sorry for the run around and thank you for the help you did provide.

**Comment by Avnsx** [comment]
Are you sure that rebooting helped, because that makes absolutely no sense. And finding the root of this issue is really important, as other people might have the same issue in the future. Also which compiled executable even worked for you the python 3.8.10 one or the 3.11.2 one?

Also this seems to be a PyAV exclusive bug, that's happening for you on both the python and on the executable versions of Fansly Downloader.

According to this issue ticket, which also looks very similar to your problem (https://github.com/PyAV-Org/PyAV/issues/361) it looks like people managed to solve the issue by installing [a older version of PyAV](https://github.com/PyAV-Org/PyAV/issues/361#issuecomment-1098811586). But the version they're referring to is a version that needs to be self-built with [Microsoft Visual C++ 14.0](https://visualstudio.microsoft.com/visual-cpp-build-tools/) first, which makes it not a acceptable solution, for the purpose I am trying to achieve by introducing PyAV to fansly downloader.

Now I am wondering if maybe on your main, real OS (not VM) you've some path in your systems environment path, that influences this issue?

Honestly I don't want to bother either, if this is a wide spread issue, someone else will probaply open a similar issue ticket or respond to this issue ticket and then I'll just pass this on to PyAV maintainers, as this is out of boundaries for me to fix.

**Comment by deadbeatdandylyon** [comment]
Okay so after I rebooted my computer 

1) first thing I did was go here - https://github.com/Avnsx/fansly-downloader 
2) the next step i did is clicked on the green icon that says "code" and selected download zip
3) unzipped the file. 
4) double checked the requirements were still installed
5) open CMD in administration went to the directory of where the fansly_downloader.py is located
6) type into cmd "Fansly_downloader.py" 

Then I received the following prompts to enter username and to type the yes or not 

![image](https://github.com/Avnsx/fansly-downloader/assets/59564520/0c093230-9970-4d35-950f-5e94523e498e)

and as you can see now it is downloading

![image](https://github.com/Avnsx/fansly-downloader/assets/59564520/7ea46355-4f4a-498b-9563-10d26ad37d9d)
_____________________________________________________________________

Then I attempted the fansly downloader.exe so I downloaded that by going here - https://github.com/Avnsx/fansly-downloader/releases/tag/v0.4 and downloading the zip file at the bottom and then unzipped, and then doubled clicked on the fansly downloader.exe and it was also able to download without any issues. 
_________________________________________
The only thing that I have noticed and it just may be a setting is when I copied the files for the fansly downloader.exe folder and moved it into another drive and directory that had already containing files of the same creator it seems to be stuck 

![image](https://github.com/Avnsx/fansly-downloader/assets/59564520/bc45b52a-2446-4ff7-ac43-147c47ded592)
