### ISSUE TITLE
Not downloading all content

### ISSUE THREAD

**Issue by deadbeatdandylyon** [Avnsx/fansly-downloader#105]
I ran the Fansly Downloader .exe for a creator and it did successfully go through. however I noticed as I was going through comparing what was downloaded, not all images were downloaded that is on her current page and also available in the tier I am subscribed to. 

So I decided to run the script again and it is still missing a section of photos. I also ran into the following error message which I don't know if this has something to do with it or not. 

![image](https://github.com/Avnsx/fansly-downloader/assets/59564520/ff2d7968-67e8-4ad8-8ebb-3a50b1b14c97)

**Comment by Avnsx** [comment]
Creator name?

**Comment by deadbeatdandylyon** [comment]
The creator name is MissionIceCream

According to her bio there should be - 603 Photos and 663 Videos

But in the folder that downloaded for Timeline - 572 photos were downloaded and 610 videos were downloaded

**Comment by Avnsx** [comment]
The error on your screenshot is such a easy fix it's literally just adding ``Image.MAX_IMAGE_PIXELS = None``, which I would've had to put into the python source, if I knew about this limit PIL safety limit upfront ..

You can press enter to continue after it errors like that, is it continuing to download other content afterwards?

If it continues to download afterwards, at most you might be missing like around 30 media items within the timeline page that errored out.

If not too bad, I'll add the support for that in the next version 0.4.1 which I'll release in about half a year

**Comment by deadbeatdandylyon** [comment]
Yes I am able to press enter and it will continue to download the rest of the content.

**Comment by Avnsx** [comment]
> Yes I am able to press enter and it will continue to download the rest of the content.

If you care so much about that couple content missing you can work your way around the bug by setting ``download_mode`` to ``Single`` and downloading the missing content manually, obviously except the insanely high resolution photo that is the root of this Error

**Comment by deadbeatdandylyon** [comment]
Well although I am a bit worried about the photos, i'm more concerned about the videos as to also be missing about 50 videos that's a bit on the wild side. I'll just look through one by one until the bug gets fixed, so thank you for your info on this

**Comment by ForcedToRock** [comment]
I'm having a similar issue of the downloader not downloading everything. I didn't get any error message though.  I didn't note the exact number of files for comparison, but as an estimate with 1 model, but old videos folder had over 200 files, while the new videos folder had 180-something, and I know I have Media Preview downloads enabled

**Comment by Avnsx** [comment]
Even if you were subscribed, you're not going to be able to download 100% of all the content available on every creator. As some of them just restrict specific content to literally be purchaseable only etc.

I do think it's very unlikely that content is missing in Timeline. As additionally before releasing I had someone test the old 0.3.5 version and the new 0.4 version on 27 different creators and it would download about the same amount of content.

Otherwise if you think it would be missing content, find the specific missing content and give me the exact post ids where that missing media is sourced from.

**Comment by Avnsx** [comment]
This whole conversation is pointless.

To help me verify that this is a genuine bug:

1. Visit the creator page.
2. Identify posts that appear to have download issues.
3. If you suspect a post is not being downloaded properly, change the download mode to "Single" and attempt to download the content from that post. If the message states "1. duplicate declined," it means you have already downloaded the post previously. If it successfully downloads the content, it indicates that the Fansly download function is working correctly. The only situation where a bug would be confirmed is if the message states "no scrapable media found" for the post you attempted to download from (and you can visibly see, that there's media attached to that post).
4. Inform me of the post IDs for such posts. If these posts are not restricted to subscribers only, I can verify that there is indeed a bug. If the posts are accessible only to subscribers, I will require access to an account with the affected content in order to confirm that it is not being downloaded and for debugging purposes, so that I can ensure compatibility with the Fansly downloader. Shoot me a e-mail with credentials to ``AvnDev@protonmail.com``

**Comment by deadbeatdandylyon** [comment]
Okay so I changed the mode to Single as you suggested

I copied the Post ID "328258312162258944" 

The result is below 

![image](https://github.com/Avnsx/fansly-downloader/assets/59564520/43fe8677-f836-4ba4-8ce1-6267ab4be5f5)

I also tried on another Post ID: "329933941077192704" and same result 

![image](https://github.com/Avnsx/fansly-downloader/assets/59564520/eb8e9f76-3ecd-4249-8eb3-c91aae8ec4d1)

I also as a test I tried using the python script and in a completely different directory for download and same results. 

I will send an email

**Comment by ForcedToRock** [comment]
So I just freshly scraped a profile, and for me, it might be based on the fact the post is accessible for everyone and not subscribers only. I downloaded a post of a free-for-all video that the Normal mode option missed.

Post ID in question: 
295387599030198272

**Comment by ForcedToRock** [comment]
It downloads when I specify the post ID and set it to Single mode, what I'm trying to say is that in Normal mode, that post was skipped. It makes me think Normal mode doesn't account for free-for-everyone posts, only subscriber-only posts.

**Comment by Avnsx** [comment]
> how does one verify if the authentication token has access to the post

Set the ``Username`` variable to ``ReplaceMe`` in the config.ini file and re-launch version 0.4. That should put it into a tutorial kind of mode, which will make it interactively help you find the authentication token corresponding to the account you want to connect it to.

**Comment by deadbeatdandylyon** [comment]
Awesome did as you suggested, I changed everything to default to "ReplaceMe" for the .exe version, I re-ran it it walked me through as you stated. for some reason it was registering firefox browser to get the configuration from so switched it to opera gx which it walked me through. after doing so I changed the config.ini download mode to "single" and still couldn't download the file.

**Comment by Avnsx** [comment]
> I copied the Post ID "328258312162258944"
> ![image](https://user-images.githubusercontent.com/59564520/246186298-43fe8677-f836-4ba4-8ce1-6267ab4be5f5.png)

I can confirm the authenticity of this bug.

Here's what's going on: The Fansly API is providing a completely random mediaId value for this particular post. Unfortunately, I designed the API parsing functionality within Fansly Downloader; to typically use this initially reported media ID and search different parts of the API response to find the highest quality content that matches the reported media ID and mimetype.

However, in the post you shared, the mediaId value is completely random. So as you might've guessed as a result, Fansly Downloader is searching everywhere for the attached content using the reported media ID, but since the actual media ID for that content is entirely different, it cannot locate the corresponding download URL. Consequently, it reports that it recognizes the presence of content but is unable to find the download location URL for it.

Fixing this will be tricky.

**Comment by deadbeatdandylyon** [comment]
Well I am happy that at the end of the day it did not come to User Error as sometimes I know that could be the issue. So I really do appreciate you taking the time to look into this for me and identify that it is an issue. So thank you very much for the help

**Comment by Avnsx** [comment]
@deadbeatdandylyon The latest commit https://github.com/Avnsx/fansly-downloader/commit/115d549204268db8a5bf6d7bd5b425c8add1d71c should've fixed all issues mentioned within this issue ticket, please verify.

You can run the latest commit by installing the python version of fansly downloader: https://github.com/Avnsx/fansly-downloader#python-version-requirements

**Comment by ForcedToRock** [comment]
I can't start the python version, it throws up an error that the config.ini file can't be read or found, even though it's in the same directory as the downloader.

**Comment by Avnsx** [comment]
@ForcedToRock If you're using a IDE, don't open it with the "open Folder" button as that will break the pathing. Open only fansly_downloader.py by double clicking on it

**Comment by ForcedToRock** [comment]
I tried the latest commit and noticed no change, it still doesn't download everything, seemingly skipping posts that aren't locked to subscriber-only.

**Comment by Avnsx** [comment]
@ForcedToRock 
> seemingly skipping posts that aren't locked to subscriber-only

Link me exact post ids, of posts which are being skipped.

> Post ID in question: 295387599030198272

Also the last post id which you linked is not true information, that video from Ah,ptik is being downloaded regardless with the media id 295387293710032896 in Timeline > Videos. And yes I downloaded it with ``download_mode`` the setting on Timeline, but regardless what I [said before](https://github.com/Avnsx/fansly-downloader/issues/105#issuecomment-1593435670) about verifying that posts can not be downloaded with ``download_mode`` on ``Single`` is also 100% correct information, because timeline, messages, single, collections all use the exact same function, to download stuff, it's all tunneled through the same thing in the codebase.

**Comment by ForcedToRock** [comment]
I can guarantee that the post ID I linked never got downloaded from the app in Normal Mode, I needed to download it via Single mode to get it.

**Comment by deadbeatdandylyon** [comment]
> @ForcedToRock @deadbeatdandylyon The latest commit [115d549](https://github.com/Avnsx/fansly-downloader/commit/115d549204268db8a5bf6d7bd5b425c8add1d71c) should've fixed all issues mentioned within this issue ticket, please verify that it downloads the missing media in the **highest possible** resolution.
> 
> You can run the latest commit by installing the python version of fansly downloader: https://github.com/Avnsx/fansly-downloader#python-version-requirements

Hello, So I know it took a while for me to provide an update on this but did some testing on it 

Before doing any testing I removed any and all versions of Fansly Downloader both .exe and .py that were installed and redownloaded first the .exe version. 

I let it run as "normal" download mode and it still didn't find all videos or pictures/ I also when completed the normal scrape i did switch over to "single" and still couldn't download the posts that I had mentioned previously. 

As a secondary test this time I used the "Fansly_downloader.py" with this one before running the normal scrape I did test to see if it could download the same post I was trying to download with the .exe version and it successfully downloaded so then I performed a full scrape with "normal" downloading using the python version and I can say that all videos have downloaded that weren't able to be downloaded before. 

so I think at this point the python version is working correctly but not the .exe 

This is my update to provide. Thank you again for your help

**Comment by Avnsx** [comment]
> so I think at this point the python version is working correctly but not the .exe

That might've not been obvious to you, but there's no way that the .exe works properly already. I only updated the python source code. The way updates are published, is that every change gets tested on the python source first and once I am about 90% what I changed there is good, I compile it and publish it as a .exe file (which I obviously didn't do yet).

So yeah, as I guessed my latest commits fixed the python source and it downloads the videos properly for you now, which is good.

I just have no clue how @ForcedToRock is still having issues, with media from Timeline.

**Comment by deadbeatdandylyon** [comment]
I didn't realize that how things work is first it's the python and then it's .exe i just wanted to provide the full update just to be safe but next time I will no for sure. 

As a helping test for you @Avnsx I went and ran a scrape using the fansly_Downloader.py on Ahptik account that @ForcedToRock is having an issue with and I set my download mode to "normal" and it was able to download the video without issue. 

![image](https://github.com/Avnsx/fansly-downloader/assets/59564520/0e68026f-24d8-4676-8c86-4a2c300b4d27)

I also switched it to single mode and downloaded the same post into another directory and it downloaded for me 

![image](https://github.com/Avnsx/fansly-downloader/assets/59564520/fa25634b-9c29-49f3-9130-e97ef1504c86)

First image from normal scrape, second image from single scrape.

**Comment by ForcedToRock** [comment]
> I didn't realize that how things work is first it's the python and then it's .exe i just wanted to provide the full update just to be safe but next time I will no for sure.
> 
> As a helping test for you @Avnsx I went and ran a scrape using the fansly_Downloader.py on Ahptik account that @ForcedToRock is having an issue with and I set my download mode to "normal" and it was able to download the video without issue.
> 
> ![image](https://user-images.githubusercontent.com/59564520/246554612-0e68026f-24d8-4676-8c86-4a2c300b4d27.png)
> 
> I also switched it to single mode and downloaded the same post into another directory and it downloaded for me
> 
> ![image](https://user-images.githubusercontent.com/59564520/246554842-fa25634b-9c29-49f3-9130-e97ef1504c86.png)
> 
> First image from normal scrape, second image from single scrape.

Was the duplicate threshold option enabled?

**Comment by Avnsx** [comment]
@ForcedToRock Please read more about duplicate_threshold here: https://github.com/Avnsx/fansly-downloader/wiki/Explanation-of-provided-programs-&-their-functionality#explanation-of-configini

**Comment by deadbeatdandylyon** [comment]
Yes I did have utilise_duplicate_threshold set to True

**Comment by ForcedToRock** [comment]
It's true for me as well, I was just trying to figure out if I did anything wrong with the config.

`show_downloads = True
download_media_previews = True
open_folder_when_finished = True
download_mode = Normal
download_directory = Local_directory
separate_messages = True
separate_previews = False
separate_timeline = True
utilise_duplicate_threshold = True`

**Comment by Avnsx** [comment]
@ForcedToRock Just try setting the threshold option to False and see if that helps you, it's not like it matters at this point.

**Comment by deadbeatdandylyon** [comment]
I don't know if this is normal but with the utilise_duplicate_treshold set to False should I be seeing this in the scrape process

![image](https://github.com/Avnsx/fansly-downloader/assets/59564520/3fba28c3-2678-427f-aa1e-6eb2f8ec99d1)

I'm just trying to help if I can and if I set mine to False should I be seeing this happen?

**Comment by Avnsx** [comment]
@deadbeatdandylyon Yes you should see that happen, because now the downloader iterates to the absolute end again, regardless if you already have above 20% of the content downloaded and stored somewhere already or not.

So now it iterates to the end > recognizes it already downloaded the content before > declines it, because we don't want it twice.

**Comment by ForcedToRock** [comment]
Crazy that I'm downloading over 40GB of content over and over to try and figure out a problem. Right now I'm trying to download with the duplicate threshold thing set to "disabled." Until that, I read this comment and thought it might not be an issue for others, but issue for me, who doesn't have the 24-hour format on my PC.

https://github.com/Avnsx/fansly-downloader/issues/104#issuecomment-1595178750

**Comment by Avnsx** [comment]
> with no AM or PM.

Yeah well I hoped that I could detect if the system is using am or pm, but I guess it's bugged out. Whatever then, don't care too much to fix it atm
https://github.com/Avnsx/fansly-downloader/blob/2e85993d9ae02c09f1d66f6388b801f296f6b1e0/fansly_downloader.py#L418-L419

**Comment by Avnsx** [comment]
The Executable file that finally fixes this bug, is now also officially released, if you're on the previous 0.4 executable version, start it and it'll automatically update itself.

Else you can download it from [releases](https://github.com/Avnsx/fansly-downloader/releases/latest).
