### ISSUE TITLE
Trojan! Automatic Configurator.exe

### ISSUE THREAD

**Issue by hejhopsa** [Avnsx/fansly-downloader#124]
Trojan stealing passwords and cookies. Dumps all browsers passwords and registry and writes it in **log_db** then sends through network

**Comment by Avnsx** [comment]
Stop using older versions of fansly scraper, then refusing to read the documentation for specific version of the program and then brainlessly calling it a trojan you pig.

Here's what automatic configurator actually does, at the time when it was the most recent version this descriptive text was officially readable on the wiki, later on it was removed due to being deprecated: https://github.com/Avnsx/fansly-downloader/wiki/Explanation-of-provided-programs-&-their-functionality/0dbc3edabb2ac2b0fb3ebcffcb31ed8e0b7e316e#2-automatic-configurator

The stuff written into log_db is never sent over the network anywhere, previously it was locally stored until the fansly account credentials could be extracted, with these credentials later on a authentication request would be sent to fansly to generate a auth token out of it.

Apart from that all versions of fansly scraper are sent to anti-virus providers for manual analysis.

Go use your last remaining two braincells on something more productive, you retard.
