### ISSUE TITLE
Why am i forced to close the Downloader after a single download?

### ISSUE THREAD

**Issue by C4uTi0N** [Avnsx/fansly-downloader#138]
When the Downloader is done downloading, the only option is "Press Enter to close...", which is super annoying when using "Single" mode to download vids that arent downloaded with "Timeline" (It's the same when downloading with "Timeline", which is also unnecessary)

**Comment by Avnsx** [comment]
1. This is not a issue with fansly downloaders functionality, so this shouldn't have been a issue ticket.
2. The feature you're requesting would mean that fansly-downloaders whole code needs to be re-written, because at the moment it's literally impossible to make the code re-start from the beginning since it's just like written from start to finish, without like any classes or anything that would allow it to loop with other creators in a efficient matter.

Deleting this issue ticket, as it's missplaced, but if you want these features to be added quickly, consider donating on https://ko-fi.com/avnsx
