### ISSUE TITLE
"updatedAt" causing unhandled TypeError exception

### ISSUE THREAD

**Issue by Blue03Si** [Avnsx/fansly-downloader#147]
Received an error Code, listed below for the creator 'milkykate'. No issue with other creators.

 [32]ERROR | 11:16 || Unexpected error during parsing Timeline content;
Traceback (most recent call last):
  File "fansly_downloader.py", line 1435, in <module>
  File "fansly_downloader.py", line 937, in parse_media_info
  File "fansly_downloader.py", line 927, in parse_variants
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by Avnsx** [comment]
https://github.com/Avnsx/fansly-downloader/blob/bc0b8d4206b93034292443860cab2783e4baec98/fansly_downloader.py#L926-L929

So in fansly-downloader, we're just catching a KeyError, which happens if the ``updatedAt`` variable is not actually existing at all.
In your case the variable ``updatedAt`` was existent, but fanslys API is just responded with nothing for the date, which makes absolutely no sense. But at the end of day, this is the Fansly API we're talking about.

With commit https://github.com/Avnsx/fansly-downloader/commit/dd7104e69f972ae66e466490b7a7349c496e1d1b this was resolved.

Please don't close this ticket, for others to see until I eventually compile and release version 0.4.2 sometime in the future.
