### ISSUE TITLE
Not downloading any content from specific model

### ISSUE THREAD

**Issue by TyranicalJim** [Avnsx/fansly-downloader#95]
So I've successfully downloaded content from other models (paid subs) but there is one account I just get 0 downloads from. 

I have a feeling it might be because the username ends with an underscore as it's the only obvious difference. 

There's no errors given, just no content downloaded.

**Comment by Avnsx** [comment]
Can't try for the model you named, because all the content is subscribers only.

Instead I tried with another model, whose username ends on a `` _`` character, called ``Ivy_`` and it worked just well for that model.

Verify that you've entered a valid authentication token that has access to the models content.

**Comment by Avnsx** [comment]
Closed due to inactivity
